### ISSUE TITLE
no esri directory

### ISSUE THREAD

**Issue by odoe** [stdavis/dojo-build-example#1]
Oops, wait a second, I don't think I can chmod on the slup script, trying again.

I got it!
Had to chmod both shell scripts, my bad. Is there a setting to do a single-file build or a couple of files?

**Comment by stdavis** [comment]
Ha! I never doubted you. You are a genius.

The settings for controlling the single file build would be the [layers property in the build profile](https://github.com/stdavis/dojo-build-example/blob/master/profiles/build.profile.js#L24). If you wanted to split it out into several files, then you would just add more layers and then load them appropriately in your build app.
